[project]
name = "propolis-wiki"
version = "0.1.1"
description = "A wiki built on HIVE"
dependencies = [
    "flask",
    "flask_session",
    "beem",
    "redis",
    "bleach"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"